sudo: required
language: java
services:
- docker
jdk:
- openjdk8
notifications:
  email: false
env:
  global:
  - secure: TctTLcBtf7qtmwr4ahcmPIqNpwdj2aF5GU+mI7e9/hzLCdO0YSu2OnT4dxAwKBh95lmFLok7T7uan1z6xLff8Y5hnjp/cJ0eF4XXW5Flz/4HDZMuDTWpC0AlZyRf83zL5j4bIxwzTMN/KJSxz9SzjVCOaV5tG22XbfGoJXMHN3tIv76kBNCi6XgqbPNHpPuA7Wqq4hl4IVaXZRnpSEY0+8Q8l1VP/wYTBWJCIHjV/hgtuRjI5Qk1d3cG8uHDHyT6aSArdRDlcy32HHbOwyAMhImtpEXgF75DQJdW+KTAWC37dYcsvJ06X7dVsKjHImvsHxJaifkt6bz9Ezo0WiyXxGAyRgGm6KRLF2C56ie9VAtxwfjLlQxOmMBzDjhC9CdraahppG1MTxWsFrPye5Pg8YaAl4aMtTy5UfRij3YjpIzEweHFaemel69EqF1Jo5hha8nhppyfxLtm8+s09Jok8jt8tT4WWnkCME9bGsgUDX8V7xuYuiQlRkuyZuGL6GgxkuErP8nf4jIcYckFsr203hTpkqiNaCGeuGDHsuXtWugdF5KGKUHrF5+tim7mo2FN8yche6IzlnZY8A9nufcEbQsTdztExhw5TlK2XxiinRFsSclEF3C7DiJofEgV4/jrx1D9sbqgJYuJEz1p9qf1tVfHa6aZep4jFF6ylTI0MsM=
  - secure: Q6UaEmh51wDemoe6ksIkc9muwYVI8dsBCr95eNyyemrphLfqSbflbyz/TFz8DulfFXwQnJ1Yh33XTWRvQUvVDwEHtrgdw1XiG6sXyeX7Rkod5w56vXJynGTK+IO/4+pbDz4NRdXQPTqOuhJ9USbOHshxww0+vXmc+8woQrCh57AOVy25chdUooV47lGTgVoV1236ohq078YErDj1tSzA8JiHeO26FQdNnx3dAk7UaWyS6n6c2F5A3s7bDRh+sxQQJgZdlIHupPSYIH9rLwE4OUsTdvGVe9+kJt/u1WFMK3/TZsAMd5+Wn1QLR3wPr0w+/GTtFlz8wdXkpJKlT3mtLuUBw+PgSQdj3/myQPUpq9MIk0HgFs6MjLpanct+S8fsnjsbbzK9NCDNfzh4NpT2AKKxQi1vaGrbT2IafPW6LzBtQjibIK21xG5/dVzV10kmKD8k7HNUoPC7ARJOrrbfwCwaHM9M9VGMG+PnOzfEdsBjp1lOdGGXXlM1gUs4FpGJwv5jxRO9on2ehUiKRUbhlUrKgqruaVJH2gq6+rqMDWZcCxUDu2iYZnif4tRLfoIu0fphT3dTCZwNzxHxFvpHTUgIDj28OiSHC7senk9ve/te3Zzk2YammqYmIcyspKpODQmZa25uoOMc5N6WBENKilVlTPAOzkAic35GSMAD4lg=
script: ".travis/build_script.sh"
after_success: ".travis/push_script.sh"
